# Generated by Django 3.1 on 2020-09-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_apps', '0005_auto_20200905_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='question',
            new_name='quiz',
        ),
    ]
