# Generated by Django 3.0.2 on 2020-09-12 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_apps', '0007_auto_20200905_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizoptions',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='all_apps.QuizQuestion'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='all_apps.Quiz'),
        ),
    ]
