# Generated by Django 3.0.2 on 2020-09-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_apps', '0008_auto_20200912_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscoredata',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
