# Generated by Django 3.0.2 on 2020-09-13 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_apps', '0010_auto_20200912_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
