# Generated by Django 3.0.2 on 2020-09-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_apps', '0011_auto_20200913_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
    ]
